spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mall?useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    addresses: 39.96.18.72
    port: 5672
    username: guest
    password: guest


#\u9A7C\u5CF0\u547D\u540D
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml
#\u4FEE\u6539\u65E5\u5FD7
logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"

wx:
  appid: wxd898fcb01713c658
  mchId: 1483469312
  mchKey: 098F6BCD4621D373CADE4E832627B4F6
  notifyUrl: http://th4wqv.natappfree.cc/pay/notify
  returnUrl: http://127.0.0.1

alipay:
  appId: 2016100100638202
  privatekey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCT322pJ+AqhLmNVh85vuGd/Yy2MicN9nBvl1D0j5rE1xYixraok2rGv8Q9DUTyOpxg9zme6vrheYiMXG5HHV1NJlHDhqjVPNokO+YXi7bVFeBHGQablWIGcguJ8ZAPK8xSAnnaaUVfXTvRuTbnJ/W+b7kcHnwHS0y1+gzdZXla777PJA8T5opIXgVzyrsCwB1LZ7X4E+AyJzndtEKGwY4vlEannSYz+4pGaHxP6gjBmQaiNzNrj14uaPQw0909BywYJviQZqxEuPSuwMRVuWgRKPS9GrleHqh6xadV0dxBLceSwrQEVvy2V8u81FXTkkMXNAyNvvlOFlbuu8m2w0QnAgMBAAECggEAaeAz2EXgzxCw+m2LdgEh8ck1Es7d/7VP09Z39GNN4VpPUx8Mca77aMqtazkxAG7OwO7CpvKAJyipiDY2D10LDM4/BMxJ3kPvvLnWiU1T30YGi2FzxbozsYG+mUoIZ5Roet+i96sgLKPIzOTcVq3Z2jyMQYHiNCbKChG7XFnnhh/Dbte3n+VTYWLFfJ+6oN2L6fIRPMSqOgu72u81w2pXCDgiqfFQm7yicD6KJRt7OcTXrYyYpPAOYuDMWgN3iLsfU243Tx6ehlT8PcSPzOYBAGyjvHALuuhF8+XWmcfUl75aGLf8he74fFDsWNRZiQdsJBC3P4GG8sNgafAnTR85IQKBgQDNPzMKlgan/giZUZ4oGdTdJonqWiYyD2A9VPdoFFZV/KfhMnCeaPG0I5bkOsJxa1cPNVkCnwOOYQLF2dHvmV76J4vr3t/cfautS6293lb9MCPIyrYtavfEvbpzCGYZu+P7o2yqMktwRokje2Q4keL3kdf67DFxAHIUv9QQJhhIQwKBgQC4cEKC3jc+Uq4SVk0uSG9nS9/OuNjYXpUGOwhmKYfySZRp/Eb8u/le09ZyjMFJDYBDDJBLSH6GhzNWt9AvseoZSc7GnTMGp++FTebvae6SvEiwjnJhmRchCXemCyH3Byjr/0x+wcStet0UDJ+nFIHET7cYJ6BO6JGgZ9veVD/YTQKBgBItQqvxVW2TRdeuLr+Gah+bxiMHENLmIbPMzoxdILhEw+lhui+NQ7qcXESiH45D31Xtd5CP3JTDaqdy/vClOJAW6IFfH5w7VPTn+t8RzcpmdQTXTwL+siquUtDVMZWd2jby5jC8e4nZ9VM7HkkUQnGCbQo/2LEVRQUpZ/J2LThZAoGAXckPuRYgBzvpsf9aXbeNlnwZgTezZEqsArAP9EsYCtbpdf9HZYp8IoEbocH7IxePagjActeZJvUm4Oi1HxucC2HhmFMlODQ68pELZiB6pPjDCaxVc1VyUmVLBw7QJZnpcB+wmSAUz5YTRveoU0B1QAq88rZrqNRQAL3vKp2ynV0CgYAsZXRSGDKDVbtrCxwZBTSHAvMWi7eaQI6fgsn3k5tGeXS2PtCAODp005pOaOC7txnPSgpebpj12Lh26KiWj89sF/GndcD7xHcp7WXHTIxuOG03oPeizM7Ml/KSZ5mhhDHcSEC2utWcpGKuRAknqwwYxznzmYkl6ykjxAgXDv2QFw==
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvjTSufEluNLH3WUDR/xw6Qvr7CW6N5qaXbo525urdavLyC6IVvMNMx9up9WfDmE6kfK8RRAi87XA9xYVbZkFbN/VMJEVhYouuuLiwEU/GsYGLbv8a2lGgc5DAGFNGvTT5J/DBoCvydasV5ACxR1KK45JQ7xyXEG1tCdg+4PtSjpzD/OpJgwYKKdkMh3l8UEANpNfwoOdr4IKVR5Ncc8eo7OsLB6uIUo6WPv5bzBZvIpNjdxWpuVjjz2iZEQjVtkse/Dbi+tedITSq5N2eZO9q8hsAYSWq6TScGmaBI063cMojPYXqzgJxM4RxG0VvSjug+EgFAZQroK4WMJumz4rlQIDAQAB
  notifyUrl: http://th4wqv.natappfree.cc/pay/notify
  returnUrl: http://127.0.0.1
